version: "3"

volumes:
  postgres-volume:
    driver: local
  alfresco_data:
    driver: local
  ass-volume:
    driver: local

services:
  alfresco:
    build: ./alfresco
    volumes:
      - alfresco_data:/usr/local/tomcat/alf_data
    deploy:
      resources:
        limits:
          memory: 1600m
    environment:
      JAVA_TOOL_OPTIONS: " -Dencryption.keystore.type=JCEKS -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding -Dencryption.keyAlgorithm=DESede -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore -Dmetadata-keystore.password=mp6yc0UD9e -Dmetadata-keystore.aliases=metadata -Dmetadata-keystore.metadata.password=oKIWzVdEdA -Dmetadata-keystore.metadata.algorithm=DESede "
      JAVA_OPTS: "\
       -Ddb.driver=org.postgresql.Driver \
       -Ddb.username=alfresco -Ddb.password=alfresco \
       -Ddb.url=jdbc:postgresql://postgres:5432/alfresco \
       -Dsolr.host=solr6 -Dsolr.port=8983 \
       -Dsolr.http.connection.timeout=1000 \
       -Dsolr.secureComms=secret \
       -Dsolr.sharedSecret=secret \
       -Dsolr.base.url=/solr \
       -Dindex.subsystem.name=solr6 \
       -Daos.baseUrlOverwrite=${ALFRESCO_URL}/alfresco/aos \
       -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\" \
       -Ddeployment.method=DOCKER_COMPOSE \
       -DlocalTransform.core-aio.url=http://transform-core-aio:8090/ \
       -Dcsrf.filter.enabled=false \
       -Dauthentication.chain=alfrescoNtlm1:alfrescoNtlm,keycloak1:keycloak \
       -Didentity-service.auth-server-url=${KEYCLOAK_URL} \
       -Didentity-service.realm=${KEYCLOAK_REALM} \
       -Didentity-service.resource=alfresco \
       -Daims.enabled=true \
       -Daims.realm=${KEYCLOAK_REALM} \
       -Daims.resource=alfresco \
       -Daims.authServerUrl=${KEYCLOAK_URL} \
       -Daims.publicClient=true \
       -XX:MinRAMPercentage=50 \
       -XX:MaxRAMPercentage=80  \
       -Dalfresco.context=alfresco \
       -Dalfresco.host=${ALFRESCO_HOST} \
       -Dalfresco.port=443 \
       -Dalfresco.protocol=https \
       -Dshare.context=share \
       -Dshare.host=${ALFRESCO_HOST} \
       -Dshare.port=443 \
       -Dshare.protocol=https \
       -Dopencmis.context.override=false \
       -Dopencmis.context.value= \
       -Dopencmis.servletpath.override=false \
       -Dopencmis.servletpath.value= \
       -Dopencmis.server.override=true \
       -Dopencmis.server.value=${ALFRESCO_URL} \
       -Dhttp.secured.session=true \
       -Dkeycloak.adapter.auth-server-url=${KEYCLOAK_URL} \
       -Dkeycloak.adapter.forced-route-url=${KEYCLOAK_URL} \
       -Dkeycloak.adapter.realm=${KEYCLOAK_REALM} \
       -Dkeycloak.adapter.resource=alfresco \
       -Dkeycloak.adapter.credentials.provider=secret \
       -Dkeycloak.adapter.credentials.secret=${KEYCLOAK_REPO_SECRET} \
       "

  transform-core-aio:
    build: ./transform
    deploy:
      resources:
        limits:
          memory: 1536m
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
    ports:
      - "8090:8090"

  share:
    build: 
      context: ./share
      args:
        - KEYCLOAK_URL=${KEYCLOAK_URL}
        - KEYCLOAK_REALM=${KEYCLOAK_REALM}
        - KEYCLOAK_SHARE_SECRET=${KEYCLOAK_SHARE_SECRET}
    deploy:
      resources:
        limits:
          memory: 1g
    environment:
      CSRF_FILTER_REFERER: "${ALFRESCO_URL}/.*"
      CSRF_FILTER_ORIGIN: "${ALFRESCO_URL}"
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: "\
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80 \
        -Dalfresco.context=alfresco \
        -Dalfresco.host=${ALFRESCO_HOST} \
        -Dalfresco.port=443 \
        -Dalfresco.protocol=https \
        -Dshare.context=share \
        -Dshare.host=${ALFRESCO_HOST} \
        -Dshare.port=443 \
        -Dshare.protocol=https \
        -Dopencmis.context.override=false \
        -Dopencmis.context.value= \
        -Dopencmis.servletpath.override=false \
        -Dopencmis.servletpath.value= \
        -Dopencmis.server.override=true \
        -Dopencmis.server.value=${ALFRESCO_URL} \
        -Dhttp.secured.session=true \
        "
  postgres:
    image: postgres:13.3
    deploy:
      resources:
        limits:
          memory: 512m
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"

  solr6:
    build: ./search-services
    deploy:
      resources:
        limits:
          memory: 2g
    volumes:
        - ass-volume:/opt/alfresco-search-services/contentstore
        - ass-volume:/opt/alfresco-search-services/data
    environment:
      # Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      # Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      # Create the default alfresco and archive cores
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      # HTTPS or SECRET
      ALFRESCO_SECURE_COMMS: "secret"
      # SHARED SECRET VALUE
      JAVA_TOOL_OPTIONS: " -Dalfresco.secureComms.secret=secret"
    ports:
      - "8083:8983" # Browser port

  activemq:
    build: ./activemq
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "8161:8161" # Web Console
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP

  proxy:
    build: ./nginx
    volumes:
      - /etc/nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - /etc/nginx/ssl/server.key:/etc/nginx/ssl/server.key
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      DISABLE_PROMETHEUS: "true"
      DISABLE_SYNCSERVICE: "true"
      DISABLE_ADW: "true"
    depends_on:
      - alfresco
    ports:
      - "8080:8080"
    links:
      - alfresco
      - share

